import {Dimensions, StyleSheet} from 'react-native';
const width = Dimensions.get('window').width;
export const styles = StyleSheet.create({
  marginBottom25: {marginBottom: 25},
  marginTop10: {marginTop: 10},
  gradLine: {
    width: '100%',
    height: 50,
    position: 'absolute',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    bottom: 0,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  noContentImage: {width: 100, height: 100, marginTop: 70},
  tag: {
    paddingHorizontal: 10,
    height: 15,
    borderRadius: 1000,
    marginHorizontal: 5,
    marginTop: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  summary: {
    marginTop: 5,
    marginHorizontal: 5,
    marginBottom: 10,
    lineHeight: 14,
  },
  marginHorizontal5: {marginHorizontal: 5},
  row: {flexDirection: 'row', alignItems: 'center'},
  calendarIcon: {width: 12, height: 12, marginHorizontal: 5},
  starIcon: {width: 20, height: 20},
  detailRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
    paddingHorizontal: 2.5,
  },
  movieImage: {
    width: '100%',
    aspectRatio: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  movieTitle: {marginTop: 5, marginHorizontal: 5},
  movieItem: {
    width: width * 0.46,
    marginHorizontal: '1%',
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 0.5,
  },
  main: {
    flexGrow: 1,
    alignItems: 'center',
  },
  topHeaderWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 60,
    width: '100%',
    marginTop: 10,
  },
  topInputWrapper: {
    width: '70%',
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 0.7,
    borderColor: '#202930',
    borderRadius: 10,
    marginLeft: 10,
  },
  searchInput: {
    height: 45,
    flex: 1,
    marginHorizontal: 10,
    paddingHorizontal: 10,
    color: 'white',
    fontFamily: 'Roboto-Light',
  },
  cross: {
    height: '100%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  crossImage: {width: 17, height: 17},
  searchImage: {width: 25, height: 25},
  mainIconWrapper: {
    width: '30%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  marginHorizontal10: {marginHorizontal: 10},
  popcornImage: {width: 40, height: 40},
  titles: {alignSelf: 'flex-start', margin: 10},
  carouselWrapper: {width: '100%', height: 200},
  carousel: {alignSelf: 'center'},
  carouselItem: {
    width: width * 0.7,
    height: 200,
    resizeMode: 'cover',
    borderRadius: 15,
  },
});
